created issue template
ykdojo/OpenStream pull request #4
Opened 2024-01-19 13:54 UTC by jasonetorres

I have built out the md file to contain a basic formate for submitting issues to the repo

2024-01-20 13:19 UTC, Jonath-z commented on ISSUETEMPLATE.md
Would you also add under the `type of issue` section `Question`?

2024-02-03 11:28 UTC, ykdojo commented
It seems like there hasn't been any activity on this for 2 weeks. Any updates @jasonetorres?

2024-02-03 11:58 UTC, jasonetorres commented
my bad YK for some reason I didn't get any of the updates on it. let me get it closed out today

2024-02-03 12:47 UTC, jasonetorres commented
added the question to the type selection!

2024-02-03 13:25 UTC, ykdojo commented
To further improve, consider creating separate templates for bug reports, feature requests, and questions. This makes it easier for users to submit their issues and helps us with better organization and automation. GitHub supports this through the .github/ISSUE_TEMPLATE directory. Thoughts?

2024-02-03 13:35 UTC, jasonetorres commented
Great idea I'll have it setup by tomorrow

2024-02-05 01:28 UTC, jasonetorres commented
ok I removed the issue template and crated seperate templates for each topic.

2024-02-05 07:25 UTC, ykdojo commented
Created this issue to see if anyone could do the next round of review: https://github.com/ykdojo/OpenStream/issues/27

2024-02-07 23:23 UTC, mehta-avi commented
From #27, to further improve:

BugReport.md:

Severity Level: A severity level tag (e.g., low, medium, high) to help streamline bugs and also ensuring that developers can effectively prioritize which bugs to work on.

Question.md:

Categories: By categorizing the questions, it makes it easy to sort them.

2024-02-10 10:44 UTC, jasonetorres reviewed
added the severity tracker to the bug report

2024-02-10 11:58 UTC, ykdojo requested changes

2024-02-10 11:58 UTC, ykdojo commented on issue templates/BugReport.md
> +name: Bug Report form
Looks like there are two names here?

2024-02-11 09:48 UTC, jasonetorres commented on issue templates/BugReport.md
> +name: Bug Report form
removed duplicate form titles

2024-02-14 01:09 UTC, ykdojo commented
https://github.com/ykdojo/OpenStream/issues/27#issuecomment-1942934296

2024-02-14 23:23 UTC, mehta-avi commented
[#27 reviewed comment](https://github.com/ykdojo/OpenStream/issues/27#issuecomment-1944985130)

2024-02-15 06:18 UTC, ykdojo approved these changes

2024-02-15 06:18 UTC, merged